version: "3"

services:
  mysql:
    image: mysql:5.7.21 # RDS MySQL version
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 10080:8080
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  mysql:
